[project]
name = 'gaming-asset-marketplace'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.asset-authenticator]
path = 'contracts/asset-authenticator.clar'
clarity_version = 2
epoch = 2.5

[contracts.asset-bridge]
path = 'contracts/asset-bridge.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
